/*
Copyright 2021 The Kubesphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubesphere/cloud-client/apis/store/v1alpha1"
	scheme "github.com/kubesphere/cloud-client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// S3ConfigsGetter has a method to return a S3ConfigInterface.
// A group's client should implement this interface.
type S3ConfigsGetter interface {
	S3Configs(namespace string) S3ConfigInterface
}

// S3ConfigInterface has methods to work with S3Config resources.
type S3ConfigInterface interface {
	Create(ctx context.Context, s3Config *v1alpha1.S3Config, opts v1.CreateOptions) (*v1alpha1.S3Config, error)
	Update(ctx context.Context, s3Config *v1alpha1.S3Config, opts v1.UpdateOptions) (*v1alpha1.S3Config, error)
	UpdateStatus(ctx context.Context, s3Config *v1alpha1.S3Config, opts v1.UpdateOptions) (*v1alpha1.S3Config, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.S3Config, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.S3ConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.S3Config, err error)
	S3ConfigExpansion
}

// s3Configs implements S3ConfigInterface
type s3Configs struct {
	client rest.Interface
	ns     string
}

// newS3Configs returns a S3Configs
func newS3Configs(c *StoreV1alpha1Client, namespace string) *s3Configs {
	return &s3Configs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the s3Config, and returns the corresponding s3Config object, and an error if there is any.
func (c *s3Configs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.S3Config, err error) {
	result = &v1alpha1.S3Config{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("s3configs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of S3Configs that match those selectors.
func (c *s3Configs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.S3ConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.S3ConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("s3configs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested s3Configs.
func (c *s3Configs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("s3configs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a s3Config and creates it.  Returns the server's representation of the s3Config, and an error, if there is any.
func (c *s3Configs) Create(ctx context.Context, s3Config *v1alpha1.S3Config, opts v1.CreateOptions) (result *v1alpha1.S3Config, err error) {
	result = &v1alpha1.S3Config{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("s3configs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(s3Config).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a s3Config and updates it. Returns the server's representation of the s3Config, and an error, if there is any.
func (c *s3Configs) Update(ctx context.Context, s3Config *v1alpha1.S3Config, opts v1.UpdateOptions) (result *v1alpha1.S3Config, err error) {
	result = &v1alpha1.S3Config{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("s3configs").
		Name(s3Config.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(s3Config).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *s3Configs) UpdateStatus(ctx context.Context, s3Config *v1alpha1.S3Config, opts v1.UpdateOptions) (result *v1alpha1.S3Config, err error) {
	result = &v1alpha1.S3Config{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("s3configs").
		Name(s3Config.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(s3Config).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the s3Config and deletes it. Returns an error if one occurs.
func (c *s3Configs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("s3configs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *s3Configs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("s3configs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched s3Config.
func (c *s3Configs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.S3Config, err error) {
	result = &v1alpha1.S3Config{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("s3configs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
