/*
Copyright 2021 The Kubesphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	storev1alpha1 "github.com/kubesphere/cloud-client/apis/store/v1alpha1"
	versioned "github.com/kubesphere/cloud-client/clientset/versioned"
	internalinterfaces "github.com/kubesphere/cloud-client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubesphere/cloud-client/listers/store/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// S3ConfigInformer provides access to a shared informer and lister for
// S3Configs.
type S3ConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.S3ConfigLister
}

type s3ConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewS3ConfigInformer constructs a new informer for S3Config type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewS3ConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredS3ConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredS3ConfigInformer constructs a new informer for S3Config type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredS3ConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StoreV1alpha1().S3Configs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StoreV1alpha1().S3Configs(namespace).Watch(context.TODO(), options)
			},
		},
		&storev1alpha1.S3Config{},
		resyncPeriod,
		indexers,
	)
}

func (f *s3ConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredS3ConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *s3ConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&storev1alpha1.S3Config{}, f.defaultInformer)
}

func (f *s3ConfigInformer) Lister() v1alpha1.S3ConfigLister {
	return v1alpha1.NewS3ConfigLister(f.Informer().GetIndexer())
}
