/*
Copyright 2021 The Kubesphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubesphere/cloud-client/apis/store/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeS3Configs implements S3ConfigInterface
type FakeS3Configs struct {
	Fake *FakeStoreV1alpha1
	ns   string
}

var s3configsResource = schema.GroupVersionResource{Group: "store.kubesphere.cloud", Version: "v1alpha1", Resource: "s3configs"}

var s3configsKind = schema.GroupVersionKind{Group: "store.kubesphere.cloud", Version: "v1alpha1", Kind: "S3Config"}

// Get takes name of the s3Config, and returns the corresponding s3Config object, and an error if there is any.
func (c *FakeS3Configs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.S3Config, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(s3configsResource, c.ns, name), &v1alpha1.S3Config{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.S3Config), err
}

// List takes label and field selectors, and returns the list of S3Configs that match those selectors.
func (c *FakeS3Configs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.S3ConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(s3configsResource, s3configsKind, c.ns, opts), &v1alpha1.S3ConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.S3ConfigList{ListMeta: obj.(*v1alpha1.S3ConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.S3ConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested s3Configs.
func (c *FakeS3Configs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(s3configsResource, c.ns, opts))

}

// Create takes the representation of a s3Config and creates it.  Returns the server's representation of the s3Config, and an error, if there is any.
func (c *FakeS3Configs) Create(ctx context.Context, s3Config *v1alpha1.S3Config, opts v1.CreateOptions) (result *v1alpha1.S3Config, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(s3configsResource, c.ns, s3Config), &v1alpha1.S3Config{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.S3Config), err
}

// Update takes the representation of a s3Config and updates it. Returns the server's representation of the s3Config, and an error, if there is any.
func (c *FakeS3Configs) Update(ctx context.Context, s3Config *v1alpha1.S3Config, opts v1.UpdateOptions) (result *v1alpha1.S3Config, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(s3configsResource, c.ns, s3Config), &v1alpha1.S3Config{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.S3Config), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeS3Configs) UpdateStatus(ctx context.Context, s3Config *v1alpha1.S3Config, opts v1.UpdateOptions) (*v1alpha1.S3Config, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(s3configsResource, "status", c.ns, s3Config), &v1alpha1.S3Config{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.S3Config), err
}

// Delete takes name of the s3Config and deletes it. Returns an error if one occurs.
func (c *FakeS3Configs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(s3configsResource, c.ns, name), &v1alpha1.S3Config{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeS3Configs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(s3configsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.S3ConfigList{})
	return err
}

// Patch applies the patch and returns the patched s3Config.
func (c *FakeS3Configs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.S3Config, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(s3configsResource, c.ns, name, pt, data, subresources...), &v1alpha1.S3Config{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.S3Config), err
}
